title: the ultimate sans
description: > # this means to ignore newlines until "baseurl:"
  he beats joejuyeong. it is a piece of cake to him because jojuyeong is as weak as hamberger :> 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Tetro53.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: wasans
tagline: jojuyeong slasher
about-description: he beats joejuyeong. it is a piece of cake to him because jojuyeong is as weak as hamberger :>  # Add Discription
pic: download.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: chamgoro@gupna.uhryeop # Add your Email address
phone: 010-1972-1121 # Add your Phone number
website: wasans.ashinunguna # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: chamgoro # Add your Github handle
twitter: '<a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">@wasans</a>' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
