title: Wendell Thomas
description: > # this means to ignore newlines until "baseurl:"
  he beats joejuyeong. it is a piece of cake to him because jojuyeong is as weak as hamberger :> 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Tetro53.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: wasans
tagline: jojuyeong slasher
about-description: he beats joejuyeong. it is a piece of cake to him because jojuyeong is as weak as hamberger :>  # Add Discription
pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: artemsheludko@tuta.io # Add your Email address
phone: 044 825 5523 # Add your Phone number
website: artemsheludko.pw # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: artemsheludko # Add your Github handle
twitter: '@artemsheludko_' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
